module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [2, "always", ["feat", "fix", "db", "perf", "refactor", "style", "docs", "test", "build", "ci", "chore", "security", "revert"]],
    "header-max-length": [2, "always", 100],
    "subject-full-stop": [2, "never", "."],
    "scope-enum": [
      2,
      "always",
      [
        "auth",
        "library",
        "books",
        "authors",
        "series",
        "cover",
        "metadata",
        "kobo",
        "opds",
        "reader",
        "collections",
        "annotations",
        "users",
        "stats",
        "notifications",
        "settings",
        "scanner",
        "email",
        "audit",
        "smart-scope",
        "types",
        "docker",
        "deps",
        "server",
        "client",
      ],
    ],
    "scope-empty": [0],
  },
};
