export const BOOK_METADATA_LOCK_FIELDS = [
  "title",
  "subtitle",
  "authors",
  "description",
  "publisher",
  "publishedYear",
  "language",
  "pageCount",
  "seriesName",
  "seriesIndex",
  "isbn13",
  "isbn10",
  "genres",
  "tags",
  "rating",
  "communityRating",
  "narrators",
  "durationSeconds",
  "abridged",
  "googleBooksId",
  "goodreadsId",
  "amazonId",
  "hardcoverId",
  "hardcoverEditionId",
  "openLibraryId",
  "itunesId",
  "audibleId",
  "koboId",
  "comicvineId",
  "ranobedbId",
  "lubimyczytacId",
  "aladinId",
  "comicIssueNumber",
  "comicVolumeName",
  "comicStoryArcs",
  "comicPencillers",
  "comicInkers",
  "comicColorists",
  "comicLetterers",
  "comicCoverArtists",
  "comicCharacters",
  "comicTeams",
  "comicLocations",
  "cover",
] as const;

export type BookMetadataLockField = (typeof BOOK_METADATA_LOCK_FIELDS)[number];
