export const PROVIDER_TIMEOUT_MS = {
  DEFAULT: 10_000,
  SCRAPE: 15_000,
  KOBO_SCRAPE: 30_000,
} as const;

export const PROVIDER_LIMITS = {
  AMAZON_MAX_RESULTS: 3,
  GOODREADS_MAX_RESULTS: 3,
  COMICVINE_MAX_RESULTS: 10,
  RANOBEDB_MAX_RESULTS: 5,
  KOBO_MAX_RESULTS: 3,
  LUBIMYCZYTAC_MAX_RESULTS: 5,
  LIBROFM_MAX_RESULTS: 3,
  DEFAULT_SEARCH_RESULTS: 10,
} as const;

export const PROVIDER_DELAYS_MS = {
  AMAZON_BETWEEN_REQUESTS: 800,
  GOODREADS_BETWEEN_REQUESTS: 600,
  HARDCOVER_RATE_LIMIT: 1_000,
  COMICVINE_VELOCITY_GUARD: 1_000,
  RANOBEDB_BETWEEN_REQUESTS: 500,
  KOBO_BETWEEN_REQUESTS: 700,
  LUBIMYCZYTAC_BETWEEN_REQUESTS: 600,
  LIBROFM_BETWEEN_REQUESTS: 300,
} as const;
